version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: platform-app:dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./:/home/gradle/project
    command: ["/bin/sh", "-c", "./gradlew bootRun"]
